---
apiVersion: v1
data:
  envoy.yaml: |+
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address: { address: 0.0.0.0, port_value: 10000 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: gateway_http
                    codec_type: AUTO
                    route_config:
                      name: malenia_backend_route
                      virtual_hosts:
                        - name: malenia_backend
                          domains: ["*"]
                          routes:
                            - match: { prefix: "/s/" }
                              route: { auto_host_rewrite: true, prefix_rewrite: "/v1.0/invoke/sample-server/method/", cluster: dapr}
                            - match: { prefix: "/sample-server/" }
                              route: { auto_host_rewrite: true, prefix_rewrite: "/v1.0/invoke/sample-server/method/", cluster: dapr }
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: dapr
        connect_timeout: 0.25s
        type: logical_dns
        lb_policy: ROUND_ROBIN
        dns_lookup_family: V4_ONLY
        upstream_connection_options:
          tcp_keepalive:
            keepalive_time: 300
        load_assignment:
          cluster_name: dapr
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 127.0.0.1
                        port_value: 3500

kind: ConfigMap
metadata:
  name: gateway-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: apigateway
  labels:
    app: malenia
    service: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      service: apigateway
  template:
    metadata:
      labels:
        app: malenia
        service: apigateway
      annotations:
        dapr.io/app-id: apigateway
        dapr.io/app-port: "10000"
        dapr.io/config: malenia-dapr-config
        dapr.io/enabled: "true"
        dapr.io/log-level: debug
    spec:
      containers:
        - name: apigateway
          image: envoyproxy/envoy:v1.24-latest
          imagePullPolicy: IfNotPresent
          args: [ "-c", "/etc/envoy/envoy.yaml", "-l", "off", "--component-log-level", "upstream:debug,connection:trace"]
          ports:
            - name: http
              containerPort: 10000
              protocol: TCP
            - name: admin
              containerPort: 8001
              protocol: TCP
            - name: daprhttp
              containerPort: 3500
              protocol: TCP
            - name: daprgrpc
              containerPort: 50001
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/envoy/
            name: gateway-config
      volumes:
        - configMap:
            defaultMode: 420
            name: gateway-config
          name: gateway-config
---

kind: Service
apiVersion: v1
metadata:
  name: apigateway
  labels:
    app: malenia
    service: apigateway
spec:
  ports:
    - port: 80
      targetPort: 10000
      protocol: TCP
      name: http
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: admin
    - port: 3500
      targetPort: 3500
      protocol: TCP
      name: daprhttp
    - port: 50001
      targetPort: 50001
      protocol: TCP
      name: daprgrpc
  selector:
    service: apigateway
